### ISSUE TITLE
Add the registration date of Agencies, regions and the Accoun Manager

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#142]

**Comment by ViTsvetkova** [comment]
To sort of the Agencies need to add additional columns in Admin Panel => Agencies:
- the registration date
- region
- Account Manager
![Screenshot_20211011-202339](https://user-images.githubusercontent.com/90184684/140077768-2c80e68e-bd91-4b7f-8221-46aac51b5d7c.png)

**Comment by Raibo** [comment]
For now, "Account manager" is just an empty string, we will add some value there when we decide what exactly we want to show there.

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com
There are Location, Account Manager, Created fields in the Agencies table.

The Location column probably replaces Region.
