### ISSUE TITLE
Allow to sorting by registration date, status of the Agency or by Account Manager

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#143]

**Comment by ViTsvetkova** [comment]
![Screenshot_20211011-202339](https://user-images.githubusercontent.com/90184684/141254924-d73072c5-c2fa-4905-a188-20f4c37c9be5.png)

**Comment by ViTsvetkova** [comment]
![Uploading IMG-20210929-WA0007.jpg…]()

**Comment by sergeyf-QA** [comment]
**Summary:**
- sortings work fine (could not check Account Manager sorting because in DB is no info about acc manager and it just fils as "" on back-end side)

**OK on DEV.**
