### ISSUE TITLE
Searching by various data

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#144]

**Comment by ViTsvetkova** [comment]
![image](https://user-images.githubusercontent.com/90184684/144401656-d0de9ef1-de0f-4efc-b3c9-79143c0082e4.png)
Need to allow searching by various data: ID number, Location, Status, etc

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
can not search at Account manager and Created columns

**Comment by alexander-plekhanov** [comment]
It'll not be possible to filter rows by date with this field. Account manager name is searchable already.
