### ISSUE TITLE
Requier a billing email on logging on

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#145]

**Comment by Raibo** [comment]
Require a billing email when creating a new root agency.

@kirillta should we also add this requirement for child-agencies?

**Comment by kirillta** [comment]
Probably, yes. We may send all invoices to it

**Comment by sergeyf-QA** [comment]
**Summary:**
- POST /{culture}/api/{v}/agent/register-master and POST /{culture}/api/{v}/agency/child-agencies/register require BillingEmail
- in case BillingEmail exists registration for new agency and child one completes well
- if user did not put the billing email then there is 400 error
`{"errors":{"Agency.BillingEmail":["The BillingEmail field is required."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1%22,%22title%22:%22Bad Request","status":400,"instance":"/en/api/1.0/agent/register-master","spanId":"2ab1b6dbec26de48","traceId":"4d15e2a502611447b7289f9a39eb88c1","requestId":"0HMDG28CL4VGK:00000002"}`

**OK on DEV.**
