### ISSUE TITLE
Add description to each type of the Report

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#146]

**Comment by ViTsvetkova** [comment]
Please check descriptions from the 409 Issue: https://github.com/happy-travel/agent-app-project/issues/409

**Comment by alexander-plekhanov** [comment]
Added all descriptions that are provided. 
Still need some more descriptions to finish the task:
1) Direct Connectivity Agency Wise Report
2) Agencies Productivity Report
3) Full Bookings Report
4) Payable To Supplier Report
5) Finalized Bookings Report
6) VCC Bookings Report
7) Cancelled Bookings Report

**Comment by alexander-plekhanov** [comment]
Close this task as done. Open new task on having new texts.
