### ISSUE TITLE
Add a button for deleting of inactive Agency

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#147]

**Comment by Raibo** [comment]
Description:
For agencies which has `IsActive' = `fasle` and don't have any bookings only.
The endpoint should delete the agency with all it's agents.

**Comment by kirillta** [comment]
Moreover I suggest that must not be applied on fully verified agencies

**Comment by kirillta** [comment]
>The endpoint should delete the agency with all it's agents.
And delete users from Odawara as well

**Comment by Raibo** [comment]
endpoint
DELETE `/en/api/1.0/admin/agencies/{agencyId}`

**Comment by sergeyf-QA** [comment]
**Summary:**
- impossible to remove an active agency
- impossible to remove a root fully verified agency
- DELETE /{culture}/api/{v}/admin/agencies/{agencyId} deletes agencies well
- when agency is deleted then an agent is removed too

**OK on DEV.**
