### ISSUE TITLE
Add the notification of policy of cancellation

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#149]

**Comment by ViTsvetkova** [comment]
![image](https://user-images.githubusercontent.com/90184684/141247296-a1ba98b8-b6be-464d-a47b-fd78c8ed7153.png)

**Comment by AlexeyShok** [comment]
See to task https://github.com/happy-travel/ueda/issues/171 for notification messages

**Comment by Raibo** [comment]
Description:
When a booking gets cancelled, a notification about the cancellation is sent.
Need to add cancellation penalty cost into this notifications.

**Comment by Raibo** [comment]
For some reason I don't remember now, an endpoint was added to admin API which shows cancellation costs for a booking, and no mail notification was modified with such info.

Therefore email notification modifications will be done in another task:
https://github.com/happy-travel/ueda/issues/212

**Comment by DenisSychev** [comment]
GET method has been created api/{v:apiVersion}/admin/accommodations/bookings/{bookingId}/cancellation-penalty
