### ISSUE TITLE
The Preferred Payment Method field have to offer Offline, or Credit card, or Virtual account credit options.

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#158]
On https://manage-dev.happytravel.com
In Chrome, Firefox, Safari.

**Steps.**
1. Log in and go to Counterparties list (click on Counterparties button);
2. Go to the information page for any counterparty;
3. Expand the list of Preferred Payment Method field suggestions.

**Result.**
The list of Preferred Payment Method field suggestions has four options, but they are wrong. For example, if you try to use the BankTransfer or Other values the saving which this values in the Preferred Payment Method field does not work. 
PUT https://edo-dev.happytravel.com/en/api/1.0/admin/counterparties/83
Status Code: 400
Error converting value \"BankTransfer\" to type HappyTravel.Edo.Common.Enums.PaymentTypes'
Error converting value \"Other\" to type 'HappyTravel.Edo.Common.Enums.PaymentTypes'

**Expectations.**
System supports 3 different payment types (https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-kinds-and-their-contracts). These are the options that should be in the proposal.

**Comment by DenisSychev** [comment]
The list in the Preferred Payment Method field should match the list in the documentation under Booking Payment Flow https://github.com/happy-travel/edo/wiki/Counterparties-%5C-Counterparty-kinds-and-their-contracts#booking-payment-flow

**Comment by alexander-plekhanov** [comment]
Deprecated already.
