### ISSUE TITLE
Add UI for managing administrators

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#159]
Backend operations will be implemented during (for more information pls contact @AlexeyShok )

https://github.com/happy-travel/agent-app-project/issues/359

Need to add UI for them to view a list of all admins, activate and deactivate them

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com/

No possibility Activating and Deactivating the administrator - no administrator data page.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Administartors list exists
- Administrator data page is added
- there is an opportunity to change roles or activate/de-activate an administartor on administrator data page

**OK on DEV.**
