### ISSUE TITLE
Add a panel to manage existing admin roles

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#160]
There is a set of CRUD operations available for admin roles:

`api/{v:apiVersion}/admin/administrator-roles`

Need to add a page to use them. For more information and changes in endpoints if needed please contact @AlexeyShok

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
1) when I enter wrong input data updating the role - I see 'Bad request' notification
**Expected:**
- some meaningful text should be there

2) after updating (or deleting) a role user is redirected to the admin roles list BUT updated role is shown like it is not updated (looks like page autoupdating does not work)
**Expected:**
- after role updating or deleting autoupdate the admin list roles by actual data

3)  after role creation would be great to be redirected to the autoupdating admin roles list

**Comment by sergeyf-QA** [comment]
**Summary:**
- it is possible to look at, create, update and delete admin roles on https://manage-dev.happytravel.com/administrator-roles/list

**OK on DEV.**
