### ISSUE TITLE
Add missing reports to admin panel

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#162]
Reports needed (endpoints):
- `/direct-connectivity-report/payable-to-supplier`
- `direct-connectivity-report/agency-wise`
- `agencies-productivity-report`
- `full-bookings-report`
- `pending-supplier-reference-report`
- `confirmed-bookings-report`
- `finalized-bookings-report`
- `hotel-wise-booking-report`
- `cancellation-deadline-report`
- `third-party-suppliers-report`
- `vcc-bookings-report`
- `hotel-productivity-report`
- `cancelled-bookings-report`

Need to check which of them exist and add missing, remove not actual

**Comment by DenisSychev** [comment]
The finalized-bookings-report should show dates for the previous calendar month.
Do not allow the administrator to select today's date and dates in the future.

**Comment by sergeyf-QA** [comment]
@cyberkarma

**Comment by sergeyf-QA** [comment]
**Summary:**
all reports are available

**OK on DEV.**
