### ISSUE TITLE
The Counterparty/Contract tab issues at the admin panel

### ISSUE THREAD

**Issue by kirillta** [happy-travel/ueda#165]
1. An uploaded contract not shows
2. 'Upload Another Contract' must be renamed to 'Re-upload Contract'

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com
Not made the item 1: An uploaded contract does not show

**Comment by sergeyf-QA** [comment]
**Summary:**
now there is a 'View Contract' button, when pressed contract is downloaded.

**OK on DEV.**
