### ISSUE TITLE
Add UI to set roles for given administrator

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#166]
Need to add an ability to edit given administrator roles.
Backend endpoints will be implemented there:

https://github.com/happy-travel/agent-app-project/issues/358

For more information and endpoints changes if needed pls contact @AlexeyShok

**Comment by sergeyf-QA** [comment]
**Summary:**
- there is an opportunity to change roles for an administartor on administrator data page
**OK on DEV.**
