### ISSUE TITLE
The response to /system-settings/availability-search comes with status 204

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/ueda#167]
On https://manage-dev.happytravel.com/ 
In Chrome, Safari, Firefox browsers

**Steps:**

1. Log in some administrator;
2. Find counterparty by name "The Clouds company"
3. Go to the Agencies page (click on "Agencies" tab) 
4. Go to the some Agency details page (click on the agency’s name row)
5. Open browser dev. tools panel
6. Go to the Agency settings page (click on "Agency Settings" tab)
7. Fin the /system-settings/availability-search request in browser dev. tools panel 

**Expected:**
The response to /system-settings/availability-search returns agency settings, respectively has status 200

**Result:**
The response to /system-settings/availability-search comes with status 204 – no useful response, respectively a blank page in the UI.

**Comment by ViTsvetkova** [comment]
@DenisSychev can you reproduce this bug?

**Comment by kirillta** [comment]
Should be solved by Senpu service

**Comment by DenisVelinen** [comment]
The task is outdated because the /system-settings/availability-search setting is being completely redesigned. Supplier availability is now regulated by the Sunpu project. All settings to be assigned by agencies by default will redesign in the task https://github.com/happy-travel/agent-app-project/issues/1389
