### ISSUE TITLE
Add DeclineVerification button

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#169]
Need to add `decline verification` on verification panel:
![изображение](https://user-images.githubusercontent.com/43397444/134121978-3e93c431-e56f-4a00-8049-7e6f5aa2765d.png)

endpoint:

{counterpartyId}/decline-verification

**Comment by DenisSychev** [comment]
On https://manage-dev.happytravel.com

The button has been added and is only present for agencies in Pending Verification state.
