### ISSUE TITLE
Add a cancellation penalty notification to the modal window

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#171]
On https://manage-dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Login some administrator;
2. Go to the Bookings tab;
3. Find the booking by reference code DEV-HTL-TH-000VC5-01;
4. Click on the Cancel button and note the message in modal window.

**Result:**
The booking with reference code DEV-HTL-TH-000VC5-01 in cancellation deadline, so at the time of cancellation there should be a message about the amount of the penalty. There is such a message on the agency app (see pic. cancelation_message).
<img width="1157" alt="cancelation_message" src="https://user-images.githubusercontent.com/17127277/136154497-ceeb3960-9989-481b-9c32-19aaa32b794c.png">

**Expectations:**
When a booking is cancelled in the admin panel, there should also be a message in the admin panel about the penalty.

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
is no cancellation penalty on notification of the modal window

**Comment by sergeyf-QA** [comment]
**Summary:**
- now cancellation penalty exists on notification of the modal window

**OK on DEV.**
