### ISSUE TITLE
Add ID of a new Agency or Agent to the notification template to the Admin

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#172]
Need to add the ID of a new Agency to the notification to Admin
Use template ID: d-25ff2449ce9949e0aadb7bde35d6f2dc

**Comment by ViTsvetkova** [comment]
Need to add the ID of a new Agency to the notification to Admin
Use template ID: d-25ff2449ce9949e0aadb7bde35d6f2dc

**Comment by DenisSychev** [comment]
This has been added and works in all environments.
