### ISSUE TITLE
No balance after activating a deactivated counterparty

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#174]
On https://manage-dev.happytravel.com/
In Safari, Chrome

**Steps:**
1. Log in some administrator;
2. Go to Counterparties page;
3. Find the counterparty with «My test» name and go to this Counterparty;
4. Pay attention to the counterparty’s balance; 
5. Change the status to inactive (click on Deactivate button);
6. Change the status to active (click on the Activate button);
7. Pay attention to the counterparty’s balance.

**Expectations:**
After activation, the counterparty should return its current balance.

**Result:**
No balance after activating a deactivated counterparty.
It happens cause the /admin/counterparties/{{counterpartyId}}/accounts/USD/balance has an empty array in response.
![Снимок экрана 2021-09-16 в 13 41 51](https://user-images.githubusercontent.com/17127277/133600099-3050907b-f9c6-47a5-b1f5-3e44c20dcab0.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- as Counterparty logic was removed now the fix is applied on Agency page
- so, now the agency balance is shown whenever admin activates or de-activates an agency

**OK on DEV.**
