### ISSUE TITLE
Allow to change Counterparty Information values only for counterparty in Pending Verification state

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#177]
On https://manage-dev.happytravel.com/

The Counterparty Information values are shown as input fields in the Counterparty Details tab.
But administrator can change them only when the counterparty is in Pending Verification state. 
To avoid confusion in all other cases (except Pending Verification state) Counterparty Information values should be shown as text.

**Comment by alexander-plekhanov** [comment]
Task information is not actual.
