### ISSUE TITLE
Edo. Create a migration that adds a list of notification types to the administrator role

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/ueda#181]
Need create a migration that adds a list of notification types to the administrator role.

Add a field to the database model. Add values to the field for admin notifications according to the list of notification types: https://github.com/happy-travel/edo/wiki/Notifications-%5C-Notification-Center

**Comment by Raibo** [comment]
There are notifications intended for admins.
Currently, such notifications are sent to specific email lists, which are kept in Vault.

This task is first in task chain, which is intended to remove these email lists from Vault and start to form them dynamically, based on administrator roles.

Each role must have a list of notification types, which would then be sent to every admin with this role.
When the notification is sent, the list of emails then will be crated dynamically, based on which admins have a role with this particular notification type added.

This task requires the following, in the form of migrations:
1. Create a column `NotificationTypes` in table `AdministratorRoles`. Type: array of integer. These integers will be values of enum `NotificationTypes`.
2. Go to the [wiki page](https://github.com/happy-travel/edo/wiki/Notifications-%5C-Notification-Center), look which notification are meant to which admin role and add enum values of these notifications types to the newly created column `NotificationTypes`.

**Comment by Raibo** [comment]
| Admin role name | Notifications |
| --- | --- |
| Account manager| AgentInvitation, ChildAgencyInvitation, AgentSuccessfulRegistration, ChildAgencySuccessfulRegistration, AgencyActivityChanged |
| Finance manager| ExternalPaymentLinks, PaymentLinkPaidNotification, CreditCardPaymentReceived, BookingInvoice, SuccessfulPaymentReceipt |
| Booking manager| BookingCancelled, BookingFinalized, BookingStatusChanged, BookingSummaryReportForAgent |
| Auditor| |
| Accommodation duplicates corrector| BookingSummaryReportForAgent |
| Accommodation Mapping Manager| |

**Comment by DenisSychev** [comment]
In the dev environment database, the table AdministratorRoles has a column NotificationTypes, which shows the types of notifications according to the table.
