### ISSUE TITLE
Edo. Add notification type list to administrator role endpoints

### ISSUE THREAD

**Issue by AlexeyShok** [happy-travel/ueda#182]
Need add notification type list to administrator role endpoints:
GET ​/{culture}​/api​/{v}​/admin​/administrator-roles
POST ​/{culture}​/api​/{v}​/admin​/administrator-roles
PUT ​/{culture}​/api​/{v}​/admin​/administrator-roles​/{roleId}

**Comment by Raibo** [comment]
In the previous task, a column `NotificationTypes` is added to `AdministratorRoles`.

Here need to add this column to data transfer models, which are used in endpoints
```
GET ​/{culture}​/api​/{v}​/admin​/administrator-roles
POST ​/{culture}​/api​/{v}​/admin​/administrator-roles
PUT ​/{culture}​/api​/{v}​/admin​/administrator-roles​/{roleId}
```
in order to enable editing of this column's data from this admin endpoints.

**Comment by DenisSychev** [comment]
Cannot create new role POST /{culture}/api/{v}/admin/administrator-roles
A message is received in response to the request
```
{
  "status": 400,
  "detail": "A role with the same name or permission set already exists"
}
```

POST /{culture}/api/{v}/admin/administrator-roles
The body request
```
{
  "id": "7",
  "name": "New role",
  "permissions": [
    "AgentInvitation"
  ]
}
```

**Comment by DenisSychev** [comment]
Cannot to edit a previously created role PUT ​/{culture}​/api​/{v}​/admin​/administrator-roles​/{roleId}
A message is received in response to the request
```
{
  "status": 400,
  "detail": "A role with the same name or permission set already exists"
}
```

PUT ​/{culture}​/api​/{v}​/admin​/administrator-roles​/{roleId}
The body request
```
{
  "id": 10,
  "name": "string",
  "permissions": [
    "AgentInvitation"
  ]
}
```

**Comment by DenisSychev** [comment]
Cannot delete existing role DELETE /en/api/1.0/admin/agent-roles/10
A message is received in response to the request
```
{
  "status": 400,
  "detail": "A role with specified Id does not exist"
}
```

**Comment by Raibo** [comment]
There was a role with ID 10 and "AgentInvitation" permission.
Tried a PUT request.
Everything worked for me. GET request also showed that changes took place.
![image](https://user-images.githubusercontent.com/8547320/144937478-fc715a28-13c6-4324-a244-a0eda8a6cb65.png)
