### ISSUE TITLE
Remove Locality HtId field from agency data editing form

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#183]
On https://manage-dev.happytravel.com

1. Go to any agency;
2. Go to the Details tab;
3. Pay attention to the Locality HtId field.

The Locality HtId field should be removed from the agency data editing form as it duplicates the clear value in the City field. It’s unlikely that administrators will find it convenient and understandable to specify Locality HtId instead of city name.
![Снимок экрана 2021-11-15 в 09 41 23](https://user-images.githubusercontent.com/17127277/141735141-1bda3323-7456-4c96-9bac-4a11cbc92b1b.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
 - City field was removed
 - Locality field may be edited
 - Locality info is sent to the server

**OK on DEV.**
