### ISSUE TITLE
Add CRUD endpoints for editing global location markups

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/ueda#185]
Need to add a controller similar to GlobalMarkupsController with the same permissions to allow adding agent-location scoped markups.
AgentScopeType for all these markups will be the same - Location.

**Comment by sergeyf-QA** [comment]
@konstyefremov 
when I try to update existed Locality Markup at PUT /{culture}/api/{v}/admin/location-markups/{policyId}
{
  "description": "test",
  "templateId": 2,
  "templateSettings": {
    "addition": 2000
  },
  "order": 6,
  "currency": "USD",
  "locationScopeId": "Locality_614882",
  "destinationScopeId": "Locality_607184"
}

then I see
{
  "status": 400,
  "detail": "Invalid scope data"
}

**Comment by konstyefremov** [comment]
> @konstyefremov when I try to update existed Locality Markup at PUT /{culture}/api/{v}/admin/location-markups/{policyId} { "description": "test", "templateId": 2, "templateSettings": { "addition": 2000 }, "order": 6, "currency": "USD", "locationScopeId": "Locality_614882", "destinationScopeId": "Locality_607184" }
> 
> then I see { "status": 400, "detail": "Invalid scope data" }

The PR above should fix this.

**Comment by DenisSychev** [comment]
A decision was made: we won't allow Markups to be edited; to change the markup policy, you will have to delete previously created Markups and create new ones.

**Comment by konstyefremov** [comment]
> A decision was made: we won't allow Markups to be edited; to change the markup policy, you will have to delete previously created Markups and create new ones.

Does this apply to global markups only or to all markups?

The methods and endpoints for modifying markups should be removed?

**Comment by alexander-plekhanov** [comment]
Markups flow will be reworked completely soon.
