### ISSUE TITLE
Add CRUD endpoints for editing agencies markups

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#189]
Administrators need to be able to create, edit and delete markups for specific agencies (the agency page will have a special tab for this).

We need to add a controller similar to AgencyMarkup (in the agency app), but only for the administrator.

**Comment by sergeyf-QA** [comment]
@DFSko 
1) PUT /admin/agencies/801/markup-policies/338
{
  "description": "testmarkups",
  "templateId": 2,
  "templateSettings": {
    "addition": 10
  },
  "order": 7,
  "currency": "USD",
  "locationScopeId": "Locality_615101",
  "destinationScopeId": "Locality_615101"
}
returns 500 error
[500 error.txt](https://github.com/happy-travel/ueda/files/7608252/500.error.txt)


2) Are we really need "locationScopeId" field in endpoints?

**Comment by DFSko** [comment]
For agency markups locationScopeId should be agencyId, not locality htId

**Comment by sergeyf-QA** [comment]
**Summary:**
CRUD operations for markup work.

**OK on DEV.**
