### ISSUE TITLE
The list of agencies isn’t loaded on the Agencies page

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#197]
**Steps.**
1. Log in as an administrator with the role "Account manager"
```
 "administratorRoleIds": [
        2
    ],
    "permissions": [
        "AccountReplenish",
        "MarkupManagement",
        "OfflinePayment",
        "CounterpartyBalanceObservation",
        "CounterpartyBalanceReplenishAndSubtract",
        "CounterpartyToAgencyTransfer",
        "PaymentLinkGeneration",
        "BalanceManualCorrection",
        "AccountsReportGeneration"
    ]
```
2. Go to the Agencies page.

**Result.**
When the administrator go to the Agencies page the list of agencies isn’t loaded.
GET https://edo-dev.happytravel.com/en/api/1.0/admin/agencies/root-agencies has status code 403
Therefore, there is no access for working with agencies and agents.

**Ecpectations.**
The administrator with the role "Account manager" should see the list of agencies as they have permissions to work with the balance, markup.

**Comment by alexander-plekhanov** [comment]
We need to rework this role and extend it's permissions.

**Comment by DenisSychev** [comment]
Permissions **CounterpartyManagement**, **AgentManagement** have been added in Role "id": 2, "name": "finance manager" on dev. environment.

**Comment by DenisSychev** [comment]
The operations carried out in the dev. environment proved insufficient to prod. environment. The task will remain here until a final decision has been made on administrator permissions.

**Comment by DenisSychev** [comment]
Correcting this situation will be done as part of the tasks https://github.com/happy-travel/agent-app-project/issues/954 and https://github.com/happy-travel/agent-app-project/issues/955
