### ISSUE TITLE
Add the Markup settings tab for agencies

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#198]
On https://manage-dev.happytravel.com

Once methods have been created to add markups for agencies #189 the appropriate tab should be added to the agency page https://manage-dev.happytravel.com/agency

**Comment by sergeyf-QA** [comment]
**Summary:**
- Agency Markup tab is added to the Agency settings
- -it is possible to add/delete agency markups there

**OK on DEV.**
