### ISSUE TITLE
Should not be sent City, CountryCode, CountryHtId, CountryName when updating the agency info

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/ueda#200]
- try to update an agency info on agency Details page with filled locality 

**Actual result:**
- City, CountryCode, CountryHtId, CountryName is sent in PUT /{culture}/api/{v}/admin/agencies/{agencyId}
![Screenshot at Nov 25 10-34-29](https://user-images.githubusercontent.com/74529212/143398763-a9b6d11f-8146-495b-8d66-b65e43daf569.png)

**Expected result:**
- As we now use Locality data to define this info on back-end side then we don't need anymore to send City, CountryCode, CountryHtId, CountryName from front

**Comment by ViTsvetkova** [comment]
Need to delete City, CountryCode, CountryHtId, CountryName in PUT /{culture}/api/{v}/admin/agencies/{agencyId}

**Comment by Raibo** [comment]
`City`, `CountryCode`, `CountryHtId`, `CountryName` fields are not included in PUT `/{culture}/api/{v}/admin/agencies/{agencyId}` model.
These fields can be safely removed on the front end side.

**Comment by alexander-plekhanov** [comment]
Won't fix. It does not affect any data.
