### ISSUE TITLE
Need to add some loader for each Report to monitor the loading

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#201]
Need to monitor the loading of the Reports in Admin Panel

**Comment by alexander-plekhanov** [comment]
Fixed more or less. At least now it seems like something happening and not like page was frozen.

**Comment by DenisVelinen** [comment]
The beginning and end of the report loading is accompanied by a special component at the top of the window.


![Image](https://user-images.githubusercontent.com/17127277/175557587-144a44c6-52ff-450e-b6c5-ed9ee5dab239.png)
