### ISSUE TITLE
Need to add error notification if the loading of the report was cancelled

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#202]
Need to understand the status of the loading of the report.
Please add some push notification in case of errors.

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Could not download report' message appears
![image](https://user-images.githubusercontent.com/74529212/190986692-f2d6ba05-652b-45e1-b36f-a17a0776f62a.png)


**OK on DEV.**
