### ISSUE TITLE
Add the list of the notifications

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#203]
Show the notifications that the Administrator has by his Role on the main page

**Comment by ViTsvetkova** [comment]
Add the tab to show which notifications the Administrator has
![image](https://user-images.githubusercontent.com/90184684/143851107-025de99c-5703-4945-9425-81f7cb73792b.png)

**Comment by DenisSychev** [comment]
It has been done and works on https://manage-dev.happytravel.com
