### ISSUE TITLE
500 error at PUT /{culture}/api/{v}/admin/agencies/{agencyId}/markup-policies/{policyId}

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/ueda#205]
PUT /admin/agencies/801/markup-policies/341
{
"description": "testmarkups",
"templateId": 2,
"templateSettings": {
"addition": 10
},
"order": 7,
"currency": "USD",
"locationScopeId": "Locality_615101",
"destinationScopeId": "Locality_615101"
}
returns 500 error
[500 error.txt](https://github.com/happy-travel/ueda/files/7608252/500.error.txt)

https://sentry1.happytravel.com/organizations/happytravel/issues/4002/?referrer=webhooks_plugin

**Comment by sergeyf-QA** [comment]
PR is done already but still is not approved
https://github.com/happy-travel/edo/pull/1229

**Comment by mingazhev** [comment]
@sergeyf-QA the PR is merged, could you check if the error repeats?

**Comment by sergeyf-QA** [comment]
**Summary:**
- is no 500 error while PUT /{culture}/api/{v}/admin/agencies/{agencyId}/markup-policies/{policyId} executing

**OK on DEV.**
