### ISSUE TITLE
POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts doesn't allow to create a discount for global markups

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/ueda#206]
**How to reproduce:**
- execute POST /{culture}/api/{v}/admin/agencies/{agencyId}/discounts
{
  "discountPercent": 5,
  "description": "test",
  "targetMarkupId": 190
}

**Actual result:**
{
  "status": 400,
  "detail": "Cannot apply discount to non-global markup policy"
}
though markup with 190 Id is a global one

**Expected result:**
- well creation of discount for global markup policy

**Comment by DFSko** [comment]
DestinationScopeType for this markup policy is not global

**Comment by sergeyf-QA** [comment]
yeah that works fine so, I am archiving the ticket
