### ISSUE TITLE
"Unknown" instead of the new agency's balance sheet

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#207]
On https://manage-dev.happytravel.com/

**Steps:**
1. Log in some administrator;
2. In Agencies, search for an agency in Pending Verification status (for example, fab211comp);
3. Go to the agency’s details page;
4. Pay attention to the balance. 

**Result:**
"Unknown" instead of the new agency's balance sheet.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now instead of  "Balance: Unknown" is shown 'Account is not created yet'

**OK on DEV.**
