### ISSUE TITLE
{agencyId}/bookings page shows a blank screen

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/ueda#208]
**How to reproduce:**
- go to bookings tab at agency e.g. https://manage-dev.happytravel.com/agency/801/bookings

**Actual result:**
- blank screen
<img width="1440" alt="Screenshot_2021-12-08_at_12 48 22" src="https://user-images.githubusercontent.com/74529212/145188073-f6f985af-e3fd-46b4-9106-3ffe00e08d32.png">

**Expected result:**
- /bookings page shows well

**Comment by DenisSychev** [comment]
It has been fixed and works on https://manage-dev.happytravel.com/

**Comment by sergeyf-QA** [comment]
**Summary:**
- bookings page shows booking of an agency

**OK on DEV.**
