### ISSUE TITLE
Edit booking cancellation notifications: add booking cancellation cost info.

### ISSUE THREAD

**Issue by Raibo** [happy-travel/ueda#212]

**Comment by Raibo** [comment]
Cancellation cost will be sent in field 'CancellationPenalty'. 
Right next to 'Price' and in the same format.

Templates:
`d-da2c6d74ecb0466283f2b5a8116fba0f`
`d-378dbbbe87194aa1bb7dfa1338169739`

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'cancellationPenalty' is in response of GET https://edo-dev.happytravel.com/en/api/1.0/notifications and returns refunded cost

**OK on DEV.**
