### ISSUE TITLE
Lost the Details agency tab

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#215]
On https://manage-dev.happytravel.com
Log in with any administrator

1. Go to any agency's page;
2. Pay attention to which page is loaded first.

**Result.**
Lost the Details agency tab.

**Expectations.**
The agency should have a Details tab. The tab shows the details of that agency. This data comes in response to /{culture}/api/{v}/admin/agencies/{agencyId}

**Comment by sergeyf-QA** [comment]
**Summary:**
- now Details tab exists on agency page

**OK on DEV.**
