### ISSUE TITLE
Add deadline, check-in и check-out date wise selection to the bookings list

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#216]
On https://manage-dev.happytravel.com/

The ability to filter (select) bookings by:
– deadline date;
– check-in;
– check-out.

What kind of selector this will be either needs to be discussed, or it can be similar to the existing tabs or Filter Status selector.

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
could you make that in dates fields (creation, deadline, check-in, check-out) admin could choose one date on https://manage-dev.happytravel.com/bookings/list?

**Comment by sergeyf-QA** [comment]
**Summary:**
- deadline date, check-in, check-out date fields are added to https://manage-dev.happytravel.com/bookings/list page

**OK on DEV.**
