### ISSUE TITLE
Add the ability to filter bookings by hotel and supplier

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#218]
On https://manage-dev.happytravel.com/

The ability to filter (select) bookings by:
– hotel;
– supplier.

What kind of selector this will be either needs to be discussed, or it can be similar to the existing Filter Status selector.

**Comment by sergeyf-QA** [comment]
**Summary:**
- now it is possible to filter bookings by accommodation or supplier on https://manage-dev.happytravel.com/bookings/list

**OK on DEV.**
