### ISSUE TITLE
Create a drop-down menu while creating a payment link to choose NGenius or Payfort

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#219]
![image](https://user-images.githubusercontent.com/90184684/149096896-b7ef00d1-7f99-40dc-89ea-7a698c9ee992.png)
Add the drop-down menu with NGenius or Payfort selection on a Create Payment link page

**Comment by sergeyf-QA** [comment]
**Summary:**
- PAYMENT PROCESSOR PRESET field exists on https://manage-dev.happytravel.com/paymentlinks
- there is possible to choose Ngenius, Payfort or Select Payment Processor Automatically 
- automatically payment processor is Ngenius

**OK on DEV.**
