### ISSUE TITLE
Immediately after logging in (via the invitation link), the administrator doesn't see role and the list of notification types

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/ueda#220]
On https://manage-dev.happytravel.com

**Steps.**
1. A person receives an email inviting them to become an administrator with a link for authorisation;
2. When the person clicks the link, they are authorised in the admin area.

**Result.**
Immediately after logging in (via the invitation link), the administrator doesn't see role and the list of notification types. After reloading the page, everything loads.
![Bug2](https://user-images.githubusercontent.com/17127277/149291932-fbb79e9d-f501-4653-aef6-de5f003cb00f.png)

**Expectations.**
Once authorised, the administrator is logged in and immediately sees all the relevant data without having to reload the page.

**Comment by alexander-plekhanov** [comment]
I think it works now.

**Comment by DenisVelinen** [comment]
It works on DEV. and PROD. environments.
