### ISSUE TITLE
Create a new field on the page of creating payment link

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#225]
Need to add a field where an admin can input an invoice number to link with the payment link
adn keep the invoice number in a hystory
![image](https://user-images.githubusercontent.com/90184684/149729675-aa8d3e8b-7ef3-46a7-9808-d985e9ff45d0.png)

**Comment by sergeyf-QA** [comment]
@alexander-plekhanov 
1) on payment link page are two Service type fields
2) Invoice number field should be required (also update the hint - remove '(optional)' from it)
3) when all fields are filled then link sending/generating buttons are disabled

**Comment by sergeyf-QA** [comment]
**Summary:**
- on payment link page is required INVOICE NUMBER field
- data entered to this field is sent by POST /{culture}/api/{v}/external/payment-links/send and POST /{culture}/api/{v}/external/payment-links

**OK on DEV.**
