### ISSUE TITLE
Show the roles that an administrator has in the Administrators list

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#228]
We need to see the administrator's roles here:
![image](https://user-images.githubusercontent.com/90184684/149902262-7bb0903b-25df-4972-bb27-01145b018796.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- now, on https://manage-dev.happytravel.com/administrators/list also admin roles are shown

**OK on DEV.**
