### ISSUE TITLE
Add information on how the booking was paid for

### ISSUE THREAD

**Issue by DenisSychev** [happy-travel/ueda#238]
On https://manage-dev.happytravel.com/

An administrator sometimes needs to know the booking was paid for. For example, to understand the consequences of cancelling a booking. 

To do so, needs to add information about how the booking was paid for. This information is in the object in response to GET request /{culture}/api/{v}/admin/bookings/{referenceCode}. There is a variable "paymentMethod".
![Снимок экрана 2022-02-09 в 13 21 23](https://user-images.githubusercontent.com/17127277/153180472-784144fb-8bcb-4536-8f7d-5a67199d9b2b.png)

**Comment by sergeyf-QA** [comment]
**Summary:**
- 'Payment Method' is shown on booking page

**OK on DEV.**
