### ISSUE TITLE
Let to search by agencies on back-end

### ISSUE THREAD

**Issue by ViTsvetkova** [happy-travel/ueda#242]
For the task https://github.com/happy-travel/ueda/issues/239 need to add the back-end routes.

**Comment by ViTsvetkova** [comment]
was done before

**Comment by sergeyf-QA** [comment]
**Summary:**
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=name eq 'fabcomp250'
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=city eq 'Vilnius'
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=countryName eq 'Lithuania'
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=verificationState eq 'ReadOnly'
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=accountManagerName eq ''
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?$filter=accountManagerName ne ''
GET {{ edo.baseUrl }}/en/api/1.0/admin/agencies/root-agencies?filter=created eq 2022-02-16
filter fine

**OK on DEV.**
