### ISSUE TITLE
500 error when logging into the admin panel

### ISSUE THREAD

**Issue by sergeyf-QA** [happy-travel/ueda#258]
**How to reproduce:**
- log in to the admin panel

**Actual result:**
- GET https://edo-dev.happytravel.com/en/api/1.0/admin/notifications/settings returns

{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Internal Server Error","status":500,"detail":"Sequence contains more than one matching element","instance":"/en/api/1.0/admin/notifications/settings","spanId":"25360d59fbcd3163","traceId":"8fc42aa7ea7c95255e5baca2234072d7","requestId":"0HMGI3186BH39:00000005","x-request-id":["15ea0d27ad9f9a4e4c25edd4d8716709"],"StackTrace":"   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()\n   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable\u00601 source, Func\u00602 predicate, Boolean\u0026 found)\n   at HappyTravel.Edo.Api.NotificationCenter.Services.NotificationOptionsService.GetMaterializedOptions(List\u00601 userOptions, ReceiverTypes receiver) in /src/Api/NotificationCenter/Services/NotificationOptionsService.cs:line 205\n   at HappyTravel.Edo.Api.NotificationCenter.Services.NotificationOptionsService.Get(SlimAdminContext admin) in /src/Api/NotificationCenter/Services/NotificationOptionsService.cs:line 81\n   at HappyTravel.Edo.Api.Controllers.AdministratorControllers.NotificationController.GetNotificationOptions() in /src/Api/Controllers/AdministratorControllers/NotificationController.cs:line 61\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResourceFilter\u003Eg__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilder.\u003C\u003Ec.\u003C\u003CBuildPipeline\u003Eb__8_0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at HappyTravel.Edo.Api.Infrastructure.Middlewares.AgentRequestLoggingMiddleware.InvokeAsync(HttpContext context, IAgentContextInternal agentContextService) in /src/Api/Infrastructure/Middlewares/AgentRequestLoggingMiddleware.cs:line 39\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)\n   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}

<img width="1440" alt="Screenshot_2022-03-30_at_10 37 19" src="https://user-images.githubusercontent.com/74529212/160778500-7cad993d-d055-40b4-ae2a-1be7db47d971.png">

**Comment by AlexeyShok** [comment]
No error now
