### ISSUE TITLE
Confirm Manually and Reject Manually doesn't work; Confirm Manually window doesn't have the obligatory Reason field

### ISSUE THREAD

**Issue by DenisVelinen** [happy-travel/ueda#265]
On https://manage-dev.happytravel.com/

Bookings in Manual Correction Needed status can be confirmed manually (this is possible when the agent has agreed with the supplier and the hotel that the booking will take place). To manually confirm the booking you will need to fill Confirmation date and Reason.

**How to.**
1. Look for the booking with ref. code DEV-HTL-RU-000IG6-01 and go to it;
2. Click on Confirm Manually button and try to confirm the booking;
There is no obligatory Reason field in the Confirm-manually modal window
admin's POST /confirm-manually
```
{
  "confirmationDate": "2022-05-20T09:03:40.161Z",
  "reason": "string"
}
```
3. Click on Confirm Manually in the window.

Repeat these steps for Reject Manually.

**Result.**
Confirm Manually and Reject Manually doesn't work; Confirm Manually window doesn't have the obligatory Reason field

**Expectation.**
We can confirm and reject bookings manually. We show these buttons in the interface. So everything should work.

**Comment by sergeyf-QA** [comment]
**Summary:**
- Confirm Manually and Reject Manually work
- Confirm Manually sends date and reason
- Reject Manually sends reason

**OK on DEV.**
